export const DISTRIBUTED_LOCK_MODULE_OPTIONS = 'DISTRIBUTED_LOCK_MODULE_OPTIONS';
export const DEFAULT_TIMEOUT = 30000; // 30秒
export const DEFAULT_MAX_RETRIES = 3;
export const DEFAULT_RETRY_DELAY = 1000; // 1秒